-- 中文键位表：把 LazyVim 默认的英文快捷键描述替换为中文。
-- 键 = 快捷键（lazy.nvim 的 <leader> 写法），值 = 中文说明。
-- 覆盖两层显示：
--  1) `<Space>sk` 键位列表（覆盖 vim keymap 的 desc）
--  2) which-key 树（<Space>? 面板）的中文叶子
return {
  -- 文件 / 查找 (f)
  ["<leader><space>"] = "查找文件",
  ["<leader>ff"] = "查找文件",
  ["<leader>fF"] = "查找文件（当前目录）",
  ["<leader>fg"] = "查找文件（git 文件）",
  ["<leader>fb"] = "缓冲区",
  ["<leader>fB"] = "缓冲区（全部）",
  ["<leader>fc"] = "查找配置文件",
  ["<leader>fr"] = "最近文件",
  ["<leader>fR"] = "最近文件（当前目录）",
  ["<leader>fp"] = "项目",
  ["<leader>fe"] = "文件管理器（根目录）",
  ["<leader>fE"] = "文件管理器（当前目录）",
  ["<leader>e"] = "文件管理器（根目录）",
  ["<leader>E"] = "文件管理器（当前目录）",
  ["<leader>fm"] = "文件管理器（当前文件目录）",
  ["<leader>fM"] = "文件管理器（当前目录）",
  ["<leader>fn"] = "新建文件",
  ["<leader>ft"] = "终端（根目录）",
  ["<leader>fT"] = "终端（当前目录）",

  -- 搜索 (s)
  ["<leader>sk"] = "快捷键",
  ["<leader>s/"] = "搜索历史",
  ["<leader>sa"] = "自动命令",
  ["<leader>sc"] = "命令历史",
  ["<leader>sC"] = "命令",
  ["<leader>sd"] = "诊断",
  ["<leader>sD"] = "缓冲区诊断",
  ["<leader>sh"] = "帮助文档",
  ["<leader>sH"] = "高亮",
  ["<leader>si"] = "图标",
  ["<leader>sj"] = "跳转记录",
  ["<leader>sl"] = "位置列表",
  ["<leader>sM"] = "手册",
  ["<leader>sm"] = "标记",
  ["<leader>sR"] = "恢复上次搜索",
  ["<leader>sq"] = "快速修复列表",
  ["<leader>su"] = "撤销树",
  ["<leader>uC"] = "配色方案",
  ["<leader>sp"] = "搜索插件配置",
  ["<leader>sg"] = "全文搜索（根目录）",
  ["<leader>sG"] = "全文搜索（当前目录）",
  ["<leader>sB"] = "搜索已打开缓冲区",
  ["<leader>sb"] = "缓冲区行",
  ["<leader>sw"] = "选中内容或词（根目录）",
  ["<leader>sW"] = "选中内容或词（当前目录）",
  ["<leader>sr"] = "搜索替换",
  ["<leader>s\""] = "寄存器",
  ["<leader>/"] = "全文搜索（根目录）",
  ["<leader>:"] = "命令历史",
  ["<leader>,"] = "缓冲区",
  ["<leader>st"] = "待办",
  ["<leader>sT"] = "待办/Fix/Fixme",
  ["<leader>sn"] = "Noice 消息",
  ["<leader>snl"] = "最后一条消息",
  ["<leader>snh"] = "消息历史",
  ["<leader>sna"] = "全部消息",
  ["<leader>snd"] = "关闭全部消息",
  ["<leader>snt"] = "消息选择",
  ["<leader>n"] = "通知历史",

  -- Git (g)
  ["<leader>gg"] = "Lazygit（根目录）",
  ["<leader>gG"] = "Lazygit（当前目录）",
  ["<leader>gl"] = "Git 日志",
  ["<leader>gL"] = "Git 日志（当前目录）",
  ["<leader>gb"] = "当前行 Git 溯源",
  ["<leader>gf"] = "当前文件历史",
  ["<leader>gB"] = "Git 浏览（打开）",
  ["<leader>gY"] = "Git 浏览（复制）",
  ["<leader>gs"] = "Git 状态",
  ["<leader>gS"] = "Git 暂存",
  ["<leader>gd"] = "Git 差异（hunks）",
  ["<leader>gD"] = "Git 差异（origin）",
  ["<leader>gi"] = "GitHub 议题（未关闭）",
  ["<leader>gI"] = "GitHub 议题（全部）",
  ["<leader>gp"] = "GitHub PR（未关闭）",
  ["<leader>gP"] = "GitHub PR（全部）",

  -- 代码 (c)
  ["<leader>cd"] = "行诊断",
  ["<leader>cf"] = "格式化",
  ["<leader>cF"] = "格式化嵌入语言",
  ["<leader>cm"] = "Mason 工具",

  -- 诊断 / 快速修复 (x)
  ["<leader>xx"] = "诊断（Trouble）",
  ["<leader>xX"] = "缓冲区诊断（Trouble）",
  ["<leader>cs"] = "文档符号（Trouble）",
  ["<leader>cS"] = "LSP 引用/定义（Trouble）",
  ["<leader>xL"] = "位置列表（Trouble）",
  ["<leader>xQ"] = "快速修复列表（Trouble）",
  ["<leader>xt"] = "待办（Trouble）",
  ["<leader>xT"] = "待办/Fix/Fixme（Trouble）",

  -- 缓冲区 (b)
  ["<leader>bb"] = "切换其他缓冲区",
  ["<leader>`"] = "切换其他缓冲区",
  ["<leader>bd"] = "删除缓冲区",
  ["<leader>bo"] = "删除其他缓冲区",
  ["<leader>bi"] = "删除隐藏缓冲区",
  ["<leader>bD"] = "删除缓冲区与窗口",
  ["<leader>bj"] = "选择缓冲区",
  ["<leader>bp"] = "固定/取消固定",
  ["<leader>bP"] = "删除未固定缓冲区",
  ["<leader>bl"] = "删除左侧缓冲区",
  ["<leader>br"] = "删除右侧缓冲区",
  ["<leader>?"] = "查看快捷键（which-key）",

  -- 窗口 / 分屏 (w)
  ["<leader>-"] = "下方分屏",
  ["<leader>|"] = "右侧分屏",
  ["<leader>wd"] = "关闭窗口",

  -- 标签页 (<leader><tab>)
  ["<leader><tab><tab>"] = "新建标签页",
  ["<leader><tab>l"] = "最后一个标签页",
  ["<leader><tab>o"] = "关闭其他标签页",
  ["<leader><tab>f"] = "第一个标签页",
  ["<leader><tab>]"] = "下一个标签页",
  ["<leader><tab>["] = "上一个标签页",
  ["<leader><tab>d"] = "关闭标签页",

  -- 界面 (u)
  ["<leader>uf"] = "格式化切换",
  ["<leader>uF"] = "格式化（保存）切换",
  ["<leader>us"] = "拼写检查",
  ["<leader>uw"] = "自动换行",
  ["<leader>uL"] = "相对行号",
  ["<leader>ud"] = "诊断显示",
  ["<leader>ul"] = "行号",
  ["<leader>uc"] = "折叠文字",
  ["<leader>uA"] = "标签栏",
  ["<leader>uT"] = "Treesitter 高亮",
  ["<leader>ub"] = "深色背景",
  ["<leader>uD"] = "暗化其他区域",
  ["<leader>ua"] = "动画",
  ["<leader>ug"] = "缩进指引",
  ["<leader>uS"] = "平滑滚动",
  ["<leader>uh"] = "内联提示",
  ["<leader>uz"] = "沉浸模式",
  ["<leader>wm"] = "窗口缩放",
  ["<leader>uZ"] = "窗口缩放",
  ["<leader>ur"] = "刷新/清除搜索高亮",
  ["<leader>ui"] = "检查光标",
  ["<leader>uI"] = "检查语法树",
  ["<leader>un"] = "关闭全部通知",

  -- 会话 / 退出 (q)
  ["<leader>qq"] = "退出全部",
  ["<leader>qs"] = "恢复会话",
  ["<leader>ql"] = "恢复上次会话",
  ["<leader>qS"] = "选择会话",
  ["<leader>qd"] = "不保存当前会话",

  -- 其它
  ["<leader>l"] = "Lazy 插件管理器",
  ["<leader>L"] = "LazyVim 更新日志",
  ["<leader>K"] = "关键词帮助",
  ["<leader>dps"] = "性能分析（缓冲区）",
  ["<leader>S"] = "选择 Scratch 缓冲区",
  ["<leader>."] = "切换 Scratch 缓冲区",
}